import type { VenueRecord } from "./types.js";

/** Mock venue data for local development. Future: venue marketplace APIs, Google Maps API */
export const MOCK_LONDON_VENUES: VenueRecord[] = [
  {
    id: "venue-001",
    name: "TechHub Shoreditch",
    address: "20 Rivington Street, Shoreditch, London EC2A 3DU",
    city: "London",
    website: "https://techhub.com/london",
    contactEmail: "events@techhub.com",
    contactPhone: "+44 20 7257 0200",
    capacity: 550,
    roomBreakdown: [
      { name: "Main Hacking Hall", capacity: 400, purpose: "primary hacking space" },
      { name: "Breakout Pods A-D", capacity: 80, purpose: "team breakout rooms" },
      { name: "Mentor Lounge", capacity: 30, purpose: "mentor office hours" },
      { name: "Judging Suite", capacity: 40, purpose: "private judging" },
      { name: "Sponsor Showcase", capacity: 50, purpose: "sponsor demos" },
    ],
    estimatedCost: 28000,
    depositRequirement: 7000,
    availabilityStatus: "available",
    wifiQuality: "excellent",
    wifiDetails: "Dedicated 2Gbps fibre with Cisco Meraki failover, tested at 500+ concurrent devices",
    transportLinks: [
      "Old Street Tube — 3 min walk",
      "Liverpool Street — 12 min walk",
      "Multiple bus routes on City Road",
    ],
    accessibility: [
      "Step-free ground floor access",
      "Accessible restrooms on all floors",
      "Hearing loop in main hall",
      "Quiet room available",
    ],
    cateringPolicy: "External caterers welcome with £500 kitchen access fee; in-house partner available",
    overnightPolicy: "24-hour access approved for hackathon events; security on-site overnight",
    securityPolicy: "CCTV, overnight security guard, badge access after 22:00",
    avEquipment: ["4K projector", "PA system", "stage lighting", "6 wireless mics", "livestream kit"],
    powerAvailability: "500+ power outlets with dedicated 100A circuit for main hall",
    insuranceRequirements: "Public liability £5M required; HackOS template accepted",
    sponsorVisibilityOptions: [
      "Branded sponsor zone (50 sqm)",
      "Stage backdrop logo placement",
      "Digital signage rotation",
    ],
    photos: [
      "https://images.example.com/techhub-main-hall.jpg",
      "https://images.example.com/techhub-breakout.jpg",
    ],
    notes: "Popular with startup hackathons. Previous AI events hosted here. Strong community vibe.",
    vibe: "startup office",
    contactPerson: "Sarah Mitchell, Events Manager",
  },
  {
    id: "venue-002",
    name: "Queen Elizabeth II Centre",
    address: "Broad Sanctuary, Westminster, London SW1P 3EE",
    city: "London",
    website: "https://qeiic.co.uk",
    contactEmail: "conferences@qeiic.co.uk",
    contactPhone: "+44 20 7798 4000",
    capacity: 800,
    roomBreakdown: [
      { name: "Westminster Hall", capacity: 500, purpose: "main event space" },
      { name: "Breakout Rooms 1-6", capacity: 120, purpose: "team rooms" },
      { name: "Executive Lounge", capacity: 40, purpose: "mentors and judges" },
      { name: "Exhibition Space", capacity: 80, purpose: "sponsor showcase" },
    ],
    estimatedCost: 45000,
    depositRequirement: 15000,
    availabilityStatus: "limited",
    wifiQuality: "good",
    wifiDetails: "Enterprise WiFi, 1Gbps shared — may need booster for 500 devices",
    transportLinks: [
      "Westminster Tube — 2 min walk",
      "Victoria Station — 10 min walk",
    ],
    accessibility: [
      "Full step-free access",
      "Multiple accessible restrooms",
      "Hearing loop throughout",
      "BSL interpreters can be arranged",
    ],
    cateringPolicy: "Exclusive in-house catering only — premium pricing",
    overnightPolicy: "Overnight access possible with special licence; additional £5,000 security fee",
    securityPolicy: "Full venue security team, bag checks, accreditation required",
    avEquipment: ["Broadcast-grade AV", "Multiple breakout AV kits", "Recording facilities"],
    powerAvailability: "Adequate for conference setup; may need supplemental power for hackathon density",
    insuranceRequirements: "Public liability £10M; additional event insurance mandatory",
    sponsorVisibilityOptions: [
      "Premium exhibition stands",
      "Main stage branding",
      "Delegate bag inserts",
    ],
    photos: ["https://images.example.com/qeiic-hall.jpg"],
    notes: "Prestigious central London location. Higher cost but excellent brand visibility.",
    vibe: "conference venue",
    hiddenCosts: ["Overnight security surcharge £5,000", "WiFi booster rental £2,000"],
    contactPerson: "David Hughes, Conference Sales",
  },
  {
    id: "venue-003",
    name: "King's College London — Bush House",
    address: "30 Aldwych, London WC2B 4BG",
    city: "London",
    website: "https://www.kcl.ac.uk/bush-house",
    contactEmail: "events@kcl.ac.uk",
    contactPhone: "+44 20 7848 7000",
    capacity: 450,
    roomBreakdown: [
      { name: "Auditorium", capacity: 300, purpose: "main hacking + ceremonies" },
      { name: "Seminar Rooms 1-4", capacity: 80, purpose: "breakout teams" },
      { name: "Faculty Lounge", capacity: 30, purpose: "mentor space" },
      { name: "Atrium", capacity: 40, purpose: "networking and sponsors" },
    ],
    estimatedCost: 18000,
    depositRequirement: 4500,
    availabilityStatus: "available",
    wifiQuality: "good",
    wifiDetails: "Eduroam + event WiFi overlay; 800Mbps, adequate for 450 devices",
    transportLinks: [
      "Temple Tube — 5 min walk",
      "Holborn Tube — 8 min walk",
      "Waterloo Station — 15 min walk",
    ],
    accessibility: [
      "Lift access to all floors",
      "Accessible restrooms",
      "Limited hearing loop (auditorium only)",
    ],
    cateringPolicy: "External caterers allowed with university approval; no alcohol without licence",
    overnightPolicy: "Overnight access not standard — requires faculty sponsor approval, historically granted for hackathons",
    securityPolicy: "University security patrols; building locked at midnight unless extended access approved",
    avEquipment: ["Projector and screen", "Basic PA", "No livestream kit included"],
    powerAvailability: "Standard academic setup — 350 outlets; extension leads recommended",
    insuranceRequirements: "University indemnity covers registered events; external PL still required",
    sponsorVisibilityOptions: [
      "Atrium banner space",
      "Programme listing",
      "Limited stage branding",
    ],
    photos: ["https://images.example.com/bush-house-auditorium.jpg"],
    notes: "Budget-friendly university option. Strong academic credibility. Overnight access needs early confirmation.",
    vibe: "university",
    contactPerson: "Dr. Emily Watson, Events Coordinator",
  },
  {
    id: "venue-004",
    name: "Protein Studios",
    address: "31 New Inn Yard, Shoreditch, London EC2A 3EY",
    city: "London",
    website: "https://proteinstudios.com",
    contactEmail: "hello@proteinstudios.com",
    contactPhone: "+44 20 7613 0700",
    capacity: 350,
    roomBreakdown: [
      { name: "Main Studio", capacity: 250, purpose: "hacking space" },
      { name: "Creative Lab", capacity: 50, purpose: "design-focused teams" },
      { name: "Green Room", capacity: 30, purpose: "mentors and organisers" },
      { name: "Rooftop Terrace", capacity: 20, purpose: "breakout and networking" },
    ],
    estimatedCost: 22000,
    depositRequirement: 5500,
    availabilityStatus: "available",
    wifiQuality: "good",
    wifiDetails: "Business-grade 1Gbps; reliable for up to 350 devices",
    transportLinks: [
      "Old Street Tube — 5 min walk",
      "Shoreditch High Street Overground — 7 min walk",
    ],
    accessibility: [
      "Ground floor step-free",
      "Upper floor accessible via lift",
      "One accessible restroom",
    ],
    cateringPolicy: "Preferred vendor list; external caterers with £300 coordination fee",
    overnightPolicy: "24-hour hire available for multi-day events",
    securityPolicy: "Keyholder on call; CCTV throughout",
    avEquipment: ["Professional sound system", "Multiple screens", "DJ booth convertible to stage"],
    powerAvailability: "350 outlets; adequate for expected attendance",
    insuranceRequirements: "Public liability £5M",
    sponsorVisibilityOptions: [
      "Branded installations in studio",
      "Projections on studio walls",
      "Rooftop banner space",
    ],
    photos: [
      "https://images.example.com/protein-main.jpg",
      "https://images.example.com/protein-rooftop.jpg",
    ],
    notes: "Creative arts space with unique vibe. Capacity slightly below target but excellent atmosphere.",
    vibe: "arts space",
    contactPerson: "Marco Reyes, Studio Manager",
  },
  {
    id: "venue-005",
    name: "CodeNode",
    address: "10 South Place, London EC2M 2RB",
    city: "London",
    website: "https://skillsmatter.com/codenode",
    contactEmail: "codenode@skillsmatter.com",
    contactPhone: "+44 20 7183 9040",
    capacity: 500,
    roomBreakdown: [
      { name: "Main Theatre (hack mode)", capacity: 350, purpose: "primary hacking" },
      { name: "Breakout Rooms 1-3", capacity: 90, purpose: "team rooms" },
      { name: "Boardroom", capacity: 20, purpose: "judging" },
      { name: " Lounge", capacity: 40, purpose: "mentors and sponsors" },
    ],
    estimatedCost: 25000,
    depositRequirement: 6250,
    availabilityStatus: "available",
    wifiQuality: "excellent",
    wifiDetails: "Developer-grade infrastructure, 2Gbps, battle-tested at Skills Matter conferences",
    transportLinks: [
      "Moorgate Tube — 2 min walk",
      "Liverpool Street — 5 min walk",
    ],
    accessibility: [
      "Full step-free access",
      "Accessible restrooms",
      "Hearing loop in theatre",
    ],
    cateringPolicy: "In-house catering partner or approved external with kitchen hire",
    overnightPolicy: "24-hour access standard for hackathon bookings",
    securityPolicy: "Reception staffed 24h during events; keycard access",
    avEquipment: ["Theatre AV system", "Recording/streaming capability", "Multiple display panels"],
    powerAvailability: "Developer event infrastructure — 500+ outlets, dedicated circuits",
    insuranceRequirements: "Public liability £5M; Skills Matter can provide template",
    sponsorVisibilityOptions: [
      "Sponsor lounge branding",
      "Stage screen logos",
      "Demo desk allocation",
    ],
    photos: ["https://images.example.com/codenode-theatre.jpg"],
    notes: "Purpose-built for developer events. Ideal hackathon infrastructure. Strong transport links.",
    vibe: "startup office",
    contactPerson: "Helen Park, Community Events Lead",
  },
  {
    id: "venue-006",
    name: "The Trampery Old Street",
    address: "239 Old Street, London EC1V 9EY",
    city: "London",
    website: "https://thetrampery.com/old-street",
    contactEmail: "oldstreet@thetrampery.com",
    capacity: 280,
    roomBreakdown: [
      { name: "Event Space", capacity: 200, purpose: "main hacking" },
      { name: "Meeting Rooms 1-2", capacity: 40, purpose: "breakouts" },
      { name: "Coworking Area", capacity: 40, purpose: "overflow and mentors" },
    ],
    estimatedCost: 15000,
    depositRequirement: 3750,
    availabilityStatus: "available",
    wifiQuality: "adequate",
    wifiDetails: "Standard coworking WiFi, 500Mbps — may struggle at full capacity",
    transportLinks: ["Old Street Tube — 1 min walk"],
    accessibility: ["Step-free access", "Accessible restroom on ground floor"],
    cateringPolicy: "External caterers welcome",
    overnightPolicy: "No overnight access — building closes at 23:00",
    securityPolicy: "Reception hours only; no overnight security",
    avEquipment: ["TV screens", "Portable PA"],
    powerAvailability: "280 outlets maximum — insufficient for 500 participants",
    insuranceRequirements: "Public liability £2M minimum",
    sponsorVisibilityOptions: ["Banner in event space", "Digital screen"],
    photos: ["https://images.example.com/trampery-old-street.jpg"],
    notes: "Affordable and well-located but too small and no overnight access for this event.",
    vibe: "startup office",
  },
];
